import { useUserContext } from 'context/user';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Layout({ children }) {
  const router = useRouter();
  const path = router.asPath;
  const basePath = path.split('/')[1];

  const { user, error } = useUserContext();
  return (
    <>
      <Head>
        <title>Expenseus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto max-w-xl px-3">
        {!error && !user ? (
          <div>Loading...</div>
        ) : (
          <nav className="mt-4">
            <ul className="flex items-center font-medium lowercase">
              <li>
                <Link href="/">
                  <a
                    className={
                      path === '/' && 'border-b-4 border-b-violet-500 pb-1'
                    }
                  >
                    Home
                  </a>
                </Link>
              </li>
              <li className="ml-4">
                <Link href="/personal">
                  <a
                    className={
                      basePath === 'personal' &&
                      'border-b-4 border-b-violet-500 pb-1'
                    }
                  >
                    Personal
                  </a>
                </Link>
              </li>
              <li className="ml-4">
                <Link href="/shared">
                  <a
                    className={
                      basePath === 'shared' &&
                      'border-b-4 border-b-violet-500 pb-1'
                    }
                  >
                    Shared
                  </a>
                </Link>
              </li>
              {!error && user && (
                <li className="ml-4">
                  <a
                    href={`${process.env.NEXT_PUBLIC_API_BASE_URL}/logout`}
                    className="inline-flex items-center rounded-md border px-3 py-2"
                  >
                    <span className="">Log out</span>
                  </a>
                </li>
              )}
            </ul>
          </nav>
        )}

        {error && error.code === 401 && (
          <main className="mt-4 h-full border-gray-600">
            <a
              href={`${process.env.NEXT_PUBLIC_API_BASE_URL}/login_google`}
              className="mt-4 inline-flex items-center rounded-md border px-3 py-2"
            >
              <img
                src="/images/google-g-logo.svg"
                alt="Google G Logo"
                height={24}
                width={24}
              />
              <span className="ml-3">Sign in with Google</span>
            </a>
          </main>
        )}

        {error && error.code !== 401 && (
          <>
            <p>There was an error. Please refresh and try again.</p>
          </>
        )}

        {!error && user && <main className="mt-4 h-full">{children}</main>}
      </div>
    </>
  );
}
